#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Oct 01 09:02:59 -05 2020
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto e6e1ae8df18d4dd597c08f004acb1a35 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot j1soc_TB_behav xil_defaultlib.j1soc_TB xil_defaultlib.glbl -log elaborate.log"
xelab -wto e6e1ae8df18d4dd597c08f004acb1a35 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot j1soc_TB_behav xil_defaultlib.j1soc_TB xil_defaultlib.glbl -log elaborate.log

